"""Add unique constraint to signal_feedback

Revision ID: 19d351d985a5
Revises: d4bdb3647f33
Create Date: 2025-11-14 22:37:47.316706

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "19d351d985a5"
down_revision: Union[str, Sequence[str], None] = "d4bdb3647f33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
