"""add bounds to forecast and create forecast_metrics table

Revision ID: 85a6f593a507
Revises: 46bcc688c67d
Create Date: 2025-11-18 12:56:18.498905

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85a6f593a507"
down_revision: Union[str, Sequence[str], None] = "46bcc688c67d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forecasts", sa.Column("upper_bound", sa.Float(), nullable=True))
    op.add_column("forecasts", sa.Column("lower_bound", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forecasts", "lower_bound")
    op.drop_column("forecasts", "upper_bound")
    # ### end Alembic commands ###
