"""Initial migration with all tables

Revision ID: d4bdb3647f33
Revises:
Create Date: 2025-11-14 21:28:13.305745

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4bdb3647f33"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dark_pool_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("signal_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("volume", sa.BIGINT(), nullable=True),
        sa.Column("avg_volume", sa.BIGINT(), nullable=True),
        sa.Column("activity_type", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "signal_time", name="_ticker_time_uc"),
    )
    op.create_index(op.f("ix_dark_pool_signals_ticker"), "dark_pool_signals", ["ticker"], unique=False)
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("forecast_date", sa.DateTime(), nullable=False),
        sa.Column("forecast_value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "forecast_date", name="_ticker_date_uc"),
    )
    op.create_index(op.f("ix_forecasts_ticker"), "forecasts", ["ticker"], unique=False)
    op.create_table(
        "intraday_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("signal_type", sa.String(length=10), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("stop_loss", sa.Float(), nullable=True),
        sa.Column("take_profit", sa.Float(), nullable=True),
        sa.Column("strategy", sa.String(length=50), nullable=True),
        sa.Column("global_bias", sa.String(length=20), nullable=True),
        sa.Column("context_score", sa.Integer(), nullable=True),
        sa.Column("related_zone_id", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "generated_at", name="_ticker_generated_uc"),
    )
    op.create_index(op.f("ix_intraday_signals_ticker"), "intraday_signals", ["ticker"], unique=False)
    op.create_table(
        "key_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("start_price", sa.Float(), nullable=False),
        sa.Column("end_price", sa.Float(), nullable=False),
        sa.Column("level_type", sa.String(length=20), nullable=False),
        sa.Column("strength", sa.BIGINT(), nullable=True),
        sa.Column("intensity", sa.Integer(), nullable=True),
        sa.Column("last_calculated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "start_price", "end_price", name="_ticker_price_uc"),
    )
    op.create_index(op.f("ix_key_levels_ticker"), "key_levels", ["ticker"], unique=False)
    op.create_table(
        "order_book_walls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("volume", sa.BIGINT(), nullable=False),
        sa.Column("wall_type", sa.String(length=10), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "wall_type", name="_ticker_wall_uc"),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("initial_capital", sa.Float(), nullable=False),
        sa.Column("current_capital", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolios_user_id"), "portfolios", ["user_id"], unique=True)
    op.create_table(
        "tracked_tickers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("figi", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("global_bias", sa.String(length=20), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("figi"),
    )
    op.create_index(op.f("ix_tracked_tickers_ticker"), "tracked_tickers", ["ticker"], unique=True)
    op.create_table(
        "trading_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("potential_profit_pct", sa.Float(), nullable=True),
        sa.Column("forecast_days", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trading_signals_ticker"), "trading_signals", ["ticker"], unique=True)
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("size_shares", sa.Integer(), nullable=True),
        sa.Column("entry_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("exit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("pnl", sa.Float(), nullable=True),
        sa.Column("related_signal_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_status"), "positions", ["status"], unique=False)
    op.create_index(op.f("ix_positions_ticker"), "positions", ["ticker"], unique=False)
    op.create_table(
        "signal_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("reaction", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["signal_id"], ["trading_signals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signal_id", "user_id", name="_signal_user_uc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signal_feedback")
    op.drop_index(op.f("ix_positions_ticker"), table_name="positions")
    op.drop_index(op.f("ix_positions_status"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_trading_signals_ticker"), table_name="trading_signals")
    op.drop_table("trading_signals")
    op.drop_index(op.f("ix_tracked_tickers_ticker"), table_name="tracked_tickers")
    op.drop_table("tracked_tickers")
    op.drop_index(op.f("ix_portfolios_user_id"), table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_table("order_book_walls")
    op.drop_index(op.f("ix_key_levels_ticker"), table_name="key_levels")
    op.drop_table("key_levels")
    op.drop_index(op.f("ix_intraday_signals_ticker"), table_name="intraday_signals")
    op.drop_table("intraday_signals")
    op.drop_index(op.f("ix_forecasts_ticker"), table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index(op.f("ix_dark_pool_signals_ticker"), table_name="dark_pool_signals")
    op.drop_table("dark_pool_signals")
    # ### end Alembic commands ###
